### ISSUE TITLE
installation fails on Windows

### ISSUE THREAD

**Issue by wiggin15** [htgoebel/gitflow#7]
easy_install and setup.py develop fail on Windows machines.
Looks like Windows doesn't like this line in MANIFEST.in

```
recursive-exclude docs/ .buildinfo
```

Output (from Cygwin, but it fails on regular cmd as well):

```
$ easy_install gitflow
Searching for gitflow
Reading http://pypi.python.org/simple/gitflow/
Reading http://github.com/htgoebel/gitflow/
Best match: gitflow 0.5.1
Downloading http://pypi.python.org/packages/source/g/gitflow/gitflow-0.5.1.zip#md5=545986954f07208015dd15669ec5aa9d
Processing gitflow-0.5.1.zip
Writing c:\cygwin\tmp\easy_install-leq1n8\gitflow-0.5.1\setup.cfg
Running gitflow-0.5.1\setup.py -q bdist_egg --dist-dir c:\cygwin\tmp\easy_install-leq1n8\gitflow-0.5.1\egg-dist-tmp-utw6bc
warning: no files found matching 'docs\make.bat'
Traceback (most recent call last):
  File "C:\Cygwin\home\Administrator\python\Scripts\easy_install-script.py", line 9, in <module>
    load_entry_point('distribute==0.6.36', 'console_scripts', 'easy_install')()
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\easy_install.py", line 1941, in main
    with_ei_usage(lambda:
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\easy_install.py", line 1922, in with_ei_usage
    return f()
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\easy_install.py", line 1945, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "C:\Cygwin\home\Administrator\python\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Cygwin\home\Administrator\python\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Cygwin\home\Administrator\python\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\easy_install.py", line 358, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\easy_install.py", line 602, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\easy_install.py", line 632, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\easy_install.py", line 827, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\easy_install.py", line 1107, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\easy_install.py", line 1093, in run_setup
    run_setup(setup_script, args)
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\sandbox.py", line 33, in run_setup
    lambda: execfile(
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\sandbox.py", line 81, in run
    return func()
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\sandbox.py", line 35, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 55, in <module>
  File "C:\Cygwin\home\Administrator\python\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Cygwin\home\Administrator\python\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Cygwin\home\Administrator\python\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\bdist_egg.py", line 172, in run
    self.run_command("egg_info")
  File "C:\Cygwin\home\Administrator\python\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Cygwin\home\Administrator\python\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\egg_info.py", line 184, in run
    self.find_sources()
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\egg_info.py", line 259, in find_sources
    mm.run()
  File "C:\Cygwin\home\Administrator\python\lib\site-packages\distribute-0.6.36-py2.7.egg\setuptools\command\egg_info.py", line 327, in run
    self.read_template()
  File "C:\Cygwin\home\Administrator\python\lib\distutils\command\sdist.py", line 316, in read_template
    self.filelist.process_template_line(line)
  File "C:\Cygwin\home\Administrator\python\lib\distutils\filelist.py", line 118, in process_template_line
    action, patterns, dir, dir_pattern = self._parse_template_line(line)
  File "C:\Cygwin\home\Administrator\python\lib\distutils\filelist.py", line 97, in _parse_template_line
    dir = convert_path(words[1])
  File "C:\Cygwin\home\Administrator\python\lib\distutils\util.py", line 201, in convert_path
    raise ValueError, "path '%s' cannot end with '/'" % pathname
ValueError: path 'docs/' cannot end with '/'
```

**Comment by htgoebel** [comment]
Can please remove the "/" in this line and try again.

**Comment by wiggin15** [comment]
yes, it works if I remove the '/' after the 'docs' (I don't know if it has any effect on the exclusions though, I don't know what the line is there for)

**Comment by htgoebel** [comment]
Great. I'll push a update immediately.

The line means: Do not include any file called ".buildinfo", which is found in the sub-directory "doc" or below, into the archive.

Interestingly the trailing slash resulted into a crash on Windows, while on Unix it resulted in a misleading "warning: no previously-included files matching '.buildinfo' found under directory 'docs/'" -- while the file was actually included.
